In [ ]:
#13.1 Fitting a Line

# Load libraries
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

# Generate features matrix, target vector
features, target = make_regression(n_samples=100,
                                   n_features=3,
                                   n_informative=1,
                                   n_targets=1,
                                   noise=0.2,
                                   coef=False,
                                   random_state=1)

# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features, target)

In [2]:
# View the intercept
model.intercept_

np.float64(-0.022228540712739386)

In [3]:
# View the feature coefficients
model.coef_

array([3.24913529e-02, 1.92375906e-02, 4.41973593e+01])

In [6]:
# Predict the target value of the first observation
model.predict(features)[0]

np.float64(39.776079378615556)

In [7]:
# Print the score of the model on the training data
print(model.score(features, target))

0.9999838705376791


In [13]:
#13.2 Handling Interactive Effects

# Load libraries
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression

# Generate features matrix, target vector
features, target = make_regression(n_samples=100,
                                   n_features=2,
                                   n_informative=2,
                                   n_targets=1,
                                   noise=0.2,
                                   coef=False,
                                   random_state=1)

# Create interaction term
interaction = PolynomialFeatures(degree=3, # بیشتزین ترکیب 3 ویژگی در تعامل
                                  include_bias=False,
                                    interaction_only=True)
features_interaction = interaction.fit_transform(features)

# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features_interaction, target)


In [11]:
# View the feature values for first observation
features[0]

array([0.0465673 , 0.80186103])

In [12]:
# Import library
import numpy as np

# For each observation, multiply the values of the first and second feature
interaction_term = np.multiply(features[:,0], features[:, 1])

# View interaction term for first observation
interaction_term[0]

np.float64(0.037340501965846186)

In [14]:
# View the values of the first observation
features_interaction[0]

array([0.0465673 , 0.80186103, 0.0373405 ])

In [19]:
#13.3 Fitting a Nonlinear Relationship

# Load library
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression

# Generate features matrix, target vector
features, target = make_regression(n_samples=100,
                                   n_features=1,
                                   n_informative=1,
                                   n_targets=1,
                                   noise=0.2,
                                   coef=False,
                                   random_state=1)

# Create polynomial features x^2 and x^3
polynomail = PolynomialFeatures(degree=3, include_bias=False)
features_polynomail = polynomail.fit_transform(features)

# Create linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features_polynomail, target)

In [20]:
# View first observation
features[0]

array([-0.61175641])

In [ ]:
# View first observation raised to the second power, x^2
features[0]**2

array([0.37424591])

In [23]:
# View first observation raised to the third power, x^3
features[0]**3

array([-0.22894734])

In [24]:
# View the first observation's values for x, x^2, and x^3
features_polynomail[0]

array([-0.61175641,  0.37424591, -0.22894734])

In [ ]:
#13.4 Reducing Variance with Regularization

# Load libraries
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression

# Generate features matrix, target vector
features, target = make_regression(n_samples=100,
                                   n_features=3,
                                   n_informative=2,
                                   n_targets=1,
                                   noise=2,
                                   coef=False,
                                   random_state=1)

# Standardize features
scaler = StandardScaler()
features_standarized = scaler.fit_transform(features)

# Create ridge regression with an alpha value
regression = Ridge(alpha=0.5 ) #penalty -> اگر بزرگ تر باشه مدل ساده تره 

# Fit the linear regression
model = regression.fit(features_standarized, target)


In [26]:
# Load library
from sklearn.linear_model import RidgeCV

# Create ridge regression with three alpha values
regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])

# Fit the linear regression
model_cv = regr_cv.fit(features, target)

# View coefficients
model_cv.coef_


array([ 0.18949374, 44.32155999, 58.00105646])

In [28]:
# View alpha
model_cv.alpha_

np.float64(0.1)

In [30]:
#13.5 Reducing Features with Lasso Regression

# Load library
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression

# Generate features matrix, target vector
features, target = make_regression(n_samples=100,
                                   n_features=3,
                                   n_informative=2,
                                   n_targets=1,
                                   noise=0.2,
                                   coef=False,
                                   random_state=1)

# Standardize features
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# Create lasso regression with alpha value
regression = Lasso(alpha=0.5)

# Fit the linear regression
model = regression.fit(features_standardized, target)

In [32]:
# View coefficients
model.coef_

array([-0.        , 43.58618393, 53.39523724])

In [33]:
# Create lasso regression with a high alpha
regression_a10 = Lasso(alpha=10)
model_a10 = regression_a10.fit(features_standardized, target)
model_a10.coef_

array([-0.        , 32.92181899, 42.73086731])