In [1]:
import numpy as np
#Capter 1.1
#Creating a Vector
vector_row = np.array([1, 2, 3])

vector_column = np.array([[1], [2], [3]])

print(vector_row)
print("- - - - - - - - - - - - - -")

print(vector_column)

[1 2 3]
- - - - - - - - - - - - - -
[[1]
 [2]
 [3]]


In [2]:
#Capter 1.2
#Creating a Matrix 

matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

print(matrix)

[[1 2]
 [1 2]
 [1 2]]


In [5]:
#Capter 1.3
#Creating a Sparse Matrix
import numpy as np
from scipy import sparse

matrix = np.array([[0, 0], 
                   [0, 1], 
                   [3, 0]])

matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)
print("- - - - - - - - - - - - - -")

matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

matrix_large_sparse = sparse.csc_matrix(matrix_large)

print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
- - - - - - - - - - - - - -
<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (2, 0)	3
  (1, 1)	1


In [6]:
#Capter 1.4
#Preallocating NumPy Arrays

vector = np.zeros(shape=5)

print(vector)
print("- - - - - - - - - - - - - -")

matrix = np.full(shape=(3, 3), fill_value=1)

print(matrix)

[0. 0. 0. 0. 0.]
- - - - - - - - - - - - - -
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
#Capter 1.5
#Selecting Elements

vector = np.array([1, 2, 3, 4, 5, 6])

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(vector[2])
print("- - - - - - - - - - - - - -")
print(matrix[1, 1])
print("- - - - - - - - - - - - - -")
print(vector[:])
print("- - - - - - - - - - - - - -")
print(vector[:3])
print("- - - - - - - - - - - - - -")
print(vector[3:])
print("- - - - - - - - - - - - - -")
print(vector[-1])
print("- - - - - - - - - - - - - -")
print(vector[::-1])
print("- - - - - - - - - - - - - -")
print(matrix[:2,:])
print("- - - - - - - - - - - - - -")
print(matrix[:,1:2])

3
- - - - - - - - - - - - - -
5
- - - - - - - - - - - - - -
[1 2 3 4 5 6]
- - - - - - - - - - - - - -
[1 2 3]
- - - - - - - - - - - - - -
[4 5 6]
- - - - - - - - - - - - - -
6
- - - - - - - - - - - - - -
[6 5 4 3 2 1]
- - - - - - - - - - - - - -
[[1 2 3]
 [4 5 6]]
- - - - - - - - - - - - - -
[[2]
 [5]
 [8]]


In [8]:
#Capter 1.6
#Describing a Matrix

matrix = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

print(matrix.shape)
print("- - - - - - - - - - - - - -")
print(matrix.size)
print("- - - - - - - - - - - - - -")
print(matrix.ndim)


(3, 4)
- - - - - - - - - - - - - -
12
- - - - - - - - - - - - - -
2


In [9]:
#Capter 1.7
#Applying Functions over Each Element

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

add_100 = lambda i: i+100

vectorized_add_100 = np.vectorize(add_100)

print(vectorized_add_100(matrix))
print("- - - - - - - - - - - - - -")

#or 
print(matrix + 100)


[[101 102 103]
 [104 105 106]
 [107 108 109]]
- - - - - - - - - - - - - -
[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [10]:
#Capter 1.8
#Finding the Maximum and Minimum Values

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(np.max(matrix))
print("- - - - - - - - - - - - - -")

print(np.min(matrix))
print("- - - - - - - - - - - - - -")

print(np.max(matrix, axis=0))
print("- - - - - - - - - - - - - -")

print(np.max(matrix, axis=1))

9
- - - - - - - - - - - - - -
1
- - - - - - - - - - - - - -
[7 8 9]
- - - - - - - - - - - - - -
[3 6 9]


In [11]:
#Capter 1.9
#Calculating the Average, Variance, and Standard Deviation

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(np.mean(matrix))
print("- - - - - - - - - - - - - -")

print(np.var(matrix))
print("- - - - - - - - - - - - - -")

print(np.std(matrix))
print("- - - - - - - - - - - - - -")

print(np.mean(matrix, axis=0))

5.0
- - - - - - - - - - - - - -
6.666666666666667
- - - - - - - - - - - - - -
2.581988897471611
- - - - - - - - - - - - - -
[4. 5. 6.]


In [12]:
#Capter 1.10
#Reshaping Arrays

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

print(matrix.reshape(2, 6))
print("- - - - - - - - - - - - - -")

print(matrix.reshape(1, -1))
print("- - - - - - - - - - - - - -")

print(matrix.reshape(12))


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
- - - - - - - - - - - - - -
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
- - - - - - - - - - - - - -
[ 1  2  3  4  5  6  7  8  9 10 11 12]
