In [25]:
#Capter 1.11
#Transposing a Vector or Matrix

import numpy as np

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(matrix.T)
print("- - - - - - - - - - - - - -")

print(np.array([1, 2, 3, 4, 5, 6]).T)
print("- - - - - - - - - - - - - -")

print(np.array([[1, 2, 3, 4, 5, 6]]).T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
- - - - - - - - - - - - - -
[1 2 3 4 5 6]
- - - - - - - - - - - - - -
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [26]:
#Capter 1.12
# Flattening a Matrix

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(matrix.flatten())
print("- - - - - - - - - - - - - -")

print(matrix.reshape(1, -1))
print("- - - - - - - - - - - - - -")

matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])

matrix_list = [matrix_a, matrix_b]

print(matrix_list)
print("- - - - - - - - - - - - - -")

print(np.ravel(matrix_list))

[1 2 3 4 5 6 7 8 9]
- - - - - - - - - - - - - -
[[1 2 3 4 5 6 7 8 9]]
- - - - - - - - - - - - - -
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
- - - - - - - - - - - - - -
[1 2 3 4 5 6 7 8]


In [4]:
#Capter 1.13
#Finding the Rank of a Matrix

matrix = np.array([[1, 1, 1],
                    [1, 1, 10],
                    [1, 1, 15]])

print(np.linalg.matrix_rank(matrix))

2


In [27]:
#Capter 1.14
#Getting the Diagonal of a Matrix

matrix = np.array([[1, 2, 3],
                    [2, 4, 6],
                    [3, 8, 9]])

print(matrix.diagonal())
print("- - - - - - - - - - - - - -")

print(matrix.diagonal(offset=1))
print("- - - - - - - - - - - - - -")

print(matrix.diagonal(offset=-1))

[1 4 9]
- - - - - - - - - - - - - -
[2 6]
- - - - - - - - - - - - - -
[2 8]


In [28]:
#Capter 1.15
#Calculating the Trace of a Matrix

matrix = np.array([[1, 2, 3],
                    [2, 4, 6],
                    [3, 8, 9]])

print(matrix.trace())
print("- - - - - - - - - - - - - -")

#or 
print(sum(matrix.diagonal()))

14
- - - - - - - - - - - - - -
14


In [30]:
#Capter 1.16
#Calculating Dot Products

vector_a = np.array([1,2,3])

vector_b = np.array([4,5,6])

print(np.dot(vector_a, vector_b))

32


In [31]:
#Capter 1.17
#Adding and Subtracting Matrices

matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

print(np.add(matrix_a, matrix_b))
print("- - - - - - - - - - - - - -")

print(np.subtract(matrix_a, matrix_b))

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
- - - - - - - - - - - - - -
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [32]:
#Capter 1.18
# Multiplying Matrices

matrix_a = np.array([[1, 1],
                     [1, 2]])

matrix_b = np.array([[1, 3],
                     [1, 2]])

print(np.dot(matrix_a, matrix_b))
print("- - - - - - - - - - - - - -")

#ot
print(matrix_a @ matrix_b)
print("- - - - - - - - - - - - - -")

# Multiply two matrices element-wise
print(matrix_a * matrix_b)

[[2 5]
 [3 7]]
- - - - - - - - - - - - - -
[[2 5]
 [3 7]]
- - - - - - - - - - - - - -
[[1 3]
 [1 4]]


In [33]:
#Capter 1.19
#1.19 Inverting a Matrix

matrix = np.array([[1, 4],
                   [2, 5]])

print(np.linalg.inv(matrix))

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


In [35]:
#Capter 1.20
#Generating Random Values

np.random.seed(0)

print(np.random.random(3))
print("- - - - - - - - - - - - - -")

print(np.random.randint(0, 200, 5))
print("- - - - - - - - - - - - - -")

# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
print(np.random.normal(0.0, 1.0, 3))
print("- - - - - - - - - - - - - -")

## Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
print(np.random.logistic(0.0, 1.0, 3))
print("- - - - - - - - - - - - - -")

# Draw three numbers greater than or equal to 1.0 and less than 2.0
print(np.random.uniform(1.0, 2.0, 3))


[0.5488135  0.71518937 0.60276338]
- - - - - - - - - - - - - -
[195 103   9  21  36]
- - - - - - - - - - - - - -
[-0.29139398 -0.13309028 -0.1730696 ]
- - - - - - - - - - - - - -
[ 1.46416405 -0.08013416 -0.4356214 ]
- - - - - - - - - - - - - -
[1.83607876 1.33739616 1.64817187]
