In [1]:
#20.1 Creating a Tensor

# Load library
import torch

# Create a vector as a row
tensor_row = torch.tensor([1, 2, 3])

# Create a vector as a column
tensor_column = torch.tensor(
    [
        [1],
        [2],
        [3]
    ]
)

In [2]:
#20.2 Creating a Tensor from NumPy

# Import libraries
import numpy as np
import torch

# Create a NumPy array
vector_row = np.array([1, 2, 3])

# Create a tensor from a NumPy array
tensor_row = torch.from_numpy(vector_row)

In [5]:
#20.3 Creating a Sparse Tensor

# Import libraries
import torch

# Create a tensor
tensor = torch.tensor(
    [
        [0, 0],
        [0, 1],
        [3, 0]
    ]
)

# Create a sparse tensor from a regular tensor
sparse_tensor = tensor.to_sparse()

print(type(tensor))
print(type(sparse_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [22]:
#20.4 Selecting Elements in a Tensor

# Load library
import torch

# Create vector tensor
vector = torch.tensor([1, 2, 3, 4, 5, 6])

# Create matrix tensor
matrix = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

# Select third element of vector
print(vector[2])

# Select second row, second column
print(matrix[1,1])

# Select all elements of a vector
print(vector[:])

# Select everything up to and including the third element
print(vector[:3])

# Select everything after the third element
print(vector[3:])

# Select the last element
print(vector[-1])

# Select the first two rows and all columns of a matrix
print(matrix[:2, :])

# Select all rows and the second column
print(matrix[:, 1:2])

# Reverse the vector
# vector[::-1] #value error

vector.flip(dims=(-1,))

tensor(3)
tensor(5)
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(6)
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2],
        [5],
        [8]])


tensor([6, 5, 4, 3, 2, 1])

In [ ]:
#20.5 Describing a Tensor

# Load library
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3], [1, 2, 3]])

# Get the shape of the tensor
print(tensor.shape)

# Get the data type of items in the tensor
print(tensor.dtype)

# Get the layout of the tensor
print(tensor.layout) #نحوه ذخیره داده‌ها در حافظه

# Get the device being used by the tensor
print(tensor.device)

torch.Size([2, 3])
torch.int64
torch.strided
cpu


In [30]:
#20.6 Applying Operations to Elements

# Load library
import torch

# Create a tensor
tensor = torch.tensor([1, 2, 3])

# Broadcast an arithmetic operation to all elements in a tensor
tensor * 100


tensor([100, 200, 300])

In [31]:
#20.7 Finding the Maximum and Minimum Values

# Load library
import torch

# Create a tensor
torch.tensor([1, 2, 3])

# Find the largest value
print(tensor.max())

# Find the smallest value
print(tensor.min())

tensor(3)
tensor(1)


In [32]:
# Create a multidimensional tensor
tensor = torch.tensor([[1, 2, 3], [1, 2, 5]])

# Find the largest value
tensor.max()

tensor(5)

In [33]:
#20.8 Reshaping Tensors

# Load library
import torch

# Create 4x3 tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Reshape tensor into 2x6 tensor
tensor.reshape(2,6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [35]:
#20.9 Transposing a Tensor

# Load library
import torch

# Create a two-dimensional tensor
tensor = torch.tensor([[[1, 2, 3]]])

# Transpose it
tensor.mT

tensor([[[1],
         [2],
         [3]]])

In [37]:
tensor.permute(*torch.arange(tensor.ndim - 1, -1, -1))

tensor([[[1]],

        [[2]],

        [[3]]])

In [39]:
# 20.10 Flattening a Tensor

# Load library
import torch

# Create tensor
tensor_1 = torch.tensor([1, 2, 3])

# Create another tensor
tensor_2 = torch.tensor([4, 5, 6])

# Calculate the dot product of the two tensors
tensor_1.dot(tensor_2)

tensor(32)

In [47]:
#20.12 Multiplying Tensors

# Load library
import torch

# Create one tensor
tensor_1 = torch.tensor([1, 2, 3])

# Create another tensor
tensor_2 = torch.tensor([4, 5, 6])

# Multiply the two tensors
print(tensor_1 * tensor_2)

# Add one tensor to another
print(tensor_1 + tensor_2)

# Subtract one tensor from another
print(tensor_1 - tensor_2)

# Divide one tensor by another
print(tensor_1 / tensor_2)

tensor([ 4, 10, 18])
tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([0.2500, 0.4000, 0.5000])
