In [4]:
#4.1 Rescaling a Feature

import numpy as np
from sklearn import preprocessing

# Create feature
feature = np.array([[-500.5],
                    [-100.1],
                    [0],
                    [100.1],
                    [900.9]])

# Create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

# Scale feature
scaled_feature = minmax_scale.fit_transform(feature)

# Show feature
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [7]:
#4.2 Standardizing a Feature

# Create feature
x = np.array([[-100.1],
              [-200.2],
              [500.5],
              [600.6],
              [9000.9]])

# Create scaler
scaler = preprocessing.StandardScaler()

# Transform the feature
standardized = scaler.fit_transform(x)

# standardized

# Print mean and standard deviation
print("Mean:", round(standardized.mean()))
print("Standard deviation:", standardized.std())

# Create scaler
robust_scaler = preprocessing.RobustScaler()

# Transform feature
robust_scaler.fit_transform(x)


Mean: 0
Standard deviation: 1.0


array([[-0.85714286],
       [-1.        ],
       [ 0.        ],
       [ 0.14285714],
       [12.13129727]])

In [14]:
#4.3 Normalizing Observations

import numpy as np
from sklearn.preprocessing import Normalizer

# Create feature matrix
features = np.array([[0.5, 0.5],
                     [1.1, 3.4],
                     [1.5, 20.2],
                     [1.63, 34.4],
                     [10.9, 3.3]])

# Create normalizer
normalizer = Normalizer(norm="l2")

# Transform feature matrix
normalizer.transform(features)

#or 
# features_l2_norm = Normalizer(norm="l2").transform(features)
#features_l2_norm

# Transform feature matrix
features_l1_norm = Normalizer(norm="l1").transform(features)

features_l1_norm

# Print sum
print("Sum of the first observation\'s values:",
features_l1_norm[0, 0] + features_l1_norm[0, 1])

Sum of the first observation's values: 1.0


In [15]:
#4.4 Generating Polynomial and Interaction Features

from sklearn.preprocessing import PolynomialFeatures

# Create feature matrix
features = np.array([[2,3],
                     [2, 3],
                     [2, 3]])

# Create PolynomialFeatures object
polynomial_interaction = PolynomialFeatures(degree=2, include_bias=False)

# Create polynomial features
polynomial_interaction.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

In [ ]:
#4.5 Transforming Features

import pandas as pd
from sklearn.preprocessing import FunctionTransformer

# Create feature matrix
features = np.array([[2, 3],
                     [2, 3],
                     [2, 3]])

# Define a simple function
def add_ten(x: int) -> int:
    return x + 10

# Create transformer
ten_transform = FunctionTransformer(add_ten)

# Transform feature matrix
ten_transform.transform(features)

# Create DataFrame
df = pd.DataFrame(features, columns=["featur_1", "featur_2"])

#Apply function
df.apply(add_ten)

array([[12, 13],
       [12, 13],
       [12, 13]])

In [25]:
#4.6 Detecting Outliers

from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

# Create simulated data
features, _ = make_blobs(n_samples=10,
                         n_features=2,
                         centers=1,
                         random_state=1)  

# Replace the first observation's values with extreme values
features[0, 0] = 10000
features[0, 1] = 10000

# Create detector
outlier_detector = EllipticEnvelope(contamination=.1)

# Fit detector
outlier_detector.fit(features)

# Predict outliers
outlier_detector.predict(features)



array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [30]:
# Create one feature
feature = features[:, 0]

# Create a function to return index of outliers
def indicies_of_outlier(x: int) -> np.array(int):
    q1, q3 = np.percentile(x, [25, 75])
    iqr = q3 - q1
    lower_bound = q1 - (iqr * 1.5)
    upper_bound = q3 + (iqr * 1.5)
    return np.where((x > upper_bound) | (x < lower_bound))

# Run function
indicies_of_outlier(feature)

(array([0], dtype=int64),)

In [32]:
#4.7 Handling Outliers

import pandas as pd 

# Create DataFrame
houses = pd.DataFrame()
houses['Prices'] = [534433, 392333, 293222, 422032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]

# Create DataFrame
houses[houses['Bathrooms'] < 20]

Prices  Bathrooms  Square_Feet
0  534433        2.0         1500
1  392333        3.5         2500
2  293222        2.0         1500

In [36]:
import numpy as np 

# Create feature based on boolean condition
houses['Outlier'] = np.where(houses['Bathrooms'] < 20, 0,1)

# Show data
houses

Prices  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0  534433        2.0         1500        0            7.313220
1  392333        3.5         2500        0            7.824046
2  293222        2.0         1500        0            7.313220
3  422032      116.0        48000        1           10.778956

In [35]:
# Log feature
houses["Log_Of_Square_Feet"] = [np.log(x) for x in houses['Square_Feet']]

# Show data
houses

Prices  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0  534433        2.0         1500        0            7.313220
1  392333        3.5         2500        0            7.824046
2  293222        2.0         1500        0            7.313220
3  422032      116.0        48000        1           10.778956

In [37]:
#4.8 Discretizating Features

import numpy as np
from sklearn.preprocessing import Binarizer

# Create feature
age = np.array([[6],
                [12],
                [20],
                [36],
                [65]])

# Create binarizer
binarizer = Binarizer(threshold=18)

# Transform feature
binarizer.fit_transform(age)

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [ ]:
# Bin feature
np.digitize(age, bins=[20, 30, 64])

array([[0],
       [0],
       [1],
       [2],
       [3]], dtype=int64)

In [39]:
# Bin feature
np.digitize(age, bins=[20, 30, 64], right=True)

array([[0],
       [0],
       [0],
       [2],
       [3]], dtype=int64)

In [40]:
# Bin feature
np.digitize(age, bins=[18])

array([[0],
       [0],
       [1],
       [1],
       [1]], dtype=int64)

In [43]:
#4.9 Grouping Observations Using Clustering

import pandas as pd 
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# Make simulated feature matrix
features, _ = make_blobs(n_samples=50,
                         n_features=2,
                         centers=3,
                         random_state=1)

# Create DataFrame
dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])

# Make k-means clusterer
clusterer = KMeans(3, random_state=0)

# Fit clusterer
clusterer.fit(features)

# Predict values
dataframe['group'] = clusterer.predict(features)

# View first few observations
dataframe.head(5)

feature_1  feature_2  group
0  -9.877554  -3.336145      2
1  -7.287210  -8.353986      0
2  -6.943061  -7.023744      0
3  -7.440167  -8.791959      0
4  -6.641388  -8.075888      0

In [45]:
#4.10 Deleting Observations with Missing Values

# Create feature matrix
features = np.array([[1.1, 11.1],
                     [2.2, 22.2],
                     [3.3, 33.3],
                     [4.4, 44.4],
                     [np.nan, 55]])

# Keep only observations that are not (denoted by ~) missing
features[~np.isnan(features).any(axis=1)]

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4]])

In [47]:
# Load data
dataframe = pd.DataFrame(features, columns=['feature_1', 'feature_2'])

# Remove observations with missing values
dataframe.dropna()

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

In [ ]:
#4.11 Imputing Missing Values
#جایگزینی داده‌های گمشده بر اساس مقادیر 5 همسایه‌های مشابه با کمترین فاصله

from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

# Make a simulated feature matrix
features, _ = make_blobs(n_samples=1000,
                         n_features=2,
                         random_state=1)

# Standardize the features
scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

# Replace the first feature's first value with a missing value
true_value = standardized_features[0,0]
standardized_features[0,0] = np.nan

# Predict the missing values in the feature matrix
knn_imputer = KNNImputer(n_neighbors=5)
features_knn_imputed = knn_imputer.fit_transform(standardized_features)

# Compare true and imputed values
print("True Value:", true_value)
print("Imputed Value:", features_knn_imputed[0,0])

True Value: 0.8730186113995938
Imputed Value: 1.0959262913919632


In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

#میانگین تمام مقادیر غیرگمشده آن ستون محاسبه می‌شود
#سپس هر مقدار گمشده در آن ستون با همان میانگین محاسبه شده جایگزین می شود

# Make a simulated feature matrix
features, _ = make_blobs(n_samples = 1000,
n_features = 2,
random_state = 1)

# Standardize the features
scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

# Replace the first feature's first value with a missing value
true_value = standardized_features[0, 0]
standardized_features[0, 0] = np.nan

# Create imputer using the "mean" strategy
mean_imputer = SimpleImputer(strategy="mean")

# Impute values
features_mean_imputed = mean_imputer.fit_transform(features)

# Compare true and imputed values
print("True Value:", true_value)
print("Imputed Value:", features_mean_imputed[0,0])

True Value: 0.8730186113995938
Imputed Value: -3.058372724614996
